/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2025-01-08 07:18:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/views/include/taglib.jsp", Long.valueOf(1736319229749L));
    _jspx_dependants.put("/WEB-INF/views/include/header_admin.jsp", Long.valueOf(1736319229748L));
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1719237896436L));
    _jspx_dependants.put("/WEB-INF/views/include/aside.jsp", Long.valueOf(1736319229747L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1719237896340L));
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/jstl-impl.jar!/META-INF/fmt.tld", Long.valueOf(1343794618000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Ample lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Ample admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Ample Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <title>Customer</title>\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/ample-admin-lite/\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"http://localhost:9999/DoAnWebCinemaimgs/favicon.png\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link href=\"http://localhost:9999/DoAnWebCinema/css/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/chartist-plugin-tooltip.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("        integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"http://localhost:9999/DoAnWebCinema/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://localhost:9999/DoAnWebCinema/css/employee.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/detail-test.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/fix-test.css\">\r\n");
      out.write("    <!-- <link href=\"../css/add-employee.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("    /* Modal header styling */\r\n");
      out.write(".modal-header {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 1.25rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal body styling */\r\n");
      out.write(".modal-body {\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Customer photo styling */\r\n");
      out.write("img.img-fluid {\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    border: 3px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Status label styling */\r\n");
      out.write(".status {\r\n");
      out.write("    font-size: 1.1rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #28a745;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Container for info boxes */\r\n");
      out.write(".info-box {\r\n");
      out.write("    background-color: #f9f9f9;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-radius: 8px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    border: 1px solid #ddd;\r\n");
      out.write("    transition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-box:hover {\r\n");
      out.write("    background-color: #f1f1f1;\r\n");
      out.write("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Label styling */\r\n");
      out.write(".label {\r\n");
      out.write("    font-size: 1rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Info details styling */\r\n");
      out.write(".info-detail {\r\n");
      out.write("    font-size: 1.1rem;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button styling */\r\n");
      out.write("button.btn-outline-primary {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: transparent;\r\n");
      out.write("    border: 2px solid #007bff;\r\n");
      out.write("    color: #007bff;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button.btn-outline-primary:hover {\r\n");
      out.write("    background-color: #007bff;\r\n");
      out.write("    color: white;\r\n");
      out.write("    border-color: #007bff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive design */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .modal-body {\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-box {\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    img.img-fluid {\r\n");
      out.write("        width: 120px;\r\n");
      out.write("        height: 120px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    	\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- <div class=\"container\" style=\"width:100%\";>\r\n");
      out.write("<h2> Bootstrap Sort Table </h2> -->\r\n");
      out.write("    <div class=\"preloader\">\r\n");
      out.write("        <div class=\"lds-ripple\">\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Main wrapper - style you can find in pages.scss -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div id=\"main-wrapper\" data-layout=\"vertical\" data-navbarbg=\"skin5\" data-sidebartype=\"full\"\r\n");
      out.write("        data-sidebar-position=\"absolute\" data-header-position=\"absolute\" data-boxed-layout=\"full\">\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Topbar header - style you can find in pages.scss -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("       \r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    	#navbarSupportedContent{\r\n");
      out.write("    		background-color: #2f323e;\r\n");
      out.write("    	}\r\n");
      out.write("    .logo-icon {\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .brand-text {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #e50914;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand:hover .brand-text {\r\n");
      out.write("        color: #f15b5b;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .navbar {\r\n");
      out.write("            padding: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .brand-text {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("        <header class=\"topbar\" data-navbarbg=\"skin5\">\r\n");
      out.write("            <nav class=\"navbar top-navbar navbar-expand-md navbar-dark\">\r\n");
      out.write("                <div class=\"navbar-header\" data-logobg=\"skin6\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("					<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("					    <div class=\"container\">\r\n");
      out.write("					        <!-- Brand and logo -->\r\n");
      out.write("					        <a class=\"navbar-brand d-flex align-items-center\" href=\"http://localhost:9999/DoAnWebCinema/admin/dashboard.htm\">\r\n");
      out.write("					            <img src=\"http://localhost:9999/DoAnWebCinema/images/logocinema.png\" alt=\"Tứ Trụ Cinema Logo\" class=\"logo-icon\" />\r\n");
      out.write("					            <span class=\"brand-text\"><b>Tứ Trụ Cinema</b></span>\r\n");
      out.write("					        </a>\r\n");
      out.write("					    </div>\r\n");
      out.write("					</nav>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <a class=\"nav-toggler waves-effect waves-light text-dark d-block d-md-none\"\r\n");
      out.write("                        href=\"javascript:void(0)\"><i class=\"ti-menu ti-close\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" id=\"navbarSupportedContent\" data-navbarbg=\"skin5\">\r\n");
      out.write("                    <ul class=\"navbar-nav d-none d-md-block d-lg-none\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-toggler nav-link waves-effect waves-light text-white\"\r\n");
      out.write("                                href=\"javascript:void(0)\"><i class=\"ti-menu ti-close\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Right side toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto d-flex align-items-center\">\r\n");
      out.write("	<li class=\"ms-auto\">\r\n");
      out.write("    <p class=\"app-search d-none d-md-block me-3\" style=\"color:white;\"><b><i>Chi nhánh ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.chiNhanh.tenChiNhanh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i></b></p>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- Search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li class=\" in\">\r\n");
      out.write("                            <form role=\"search\" class=\"app-search d-none d-md-block me-3\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Tìm kiếm...\" class=\"form-control mt-0\">\r\n");
      out.write("                                <a href=\"\" class=\"active\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"profile-pic\" href=\"#\">\r\n");
      out.write("                                <img src=\"http://localhost:9999/DoAnWebCinema/images/user.gif\" alt=\"user-img\" width=\"36\"\r\n");
      out.write("                                    class=\"img-circle\"><span class=\"text-white font-medium\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenNV}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Topbar header -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<aside class=\"left-sidebar\" data-sidebarbg=\"skin6\">\r\n");
      out.write("	<!-- Sidebar scroll-->\r\n");
      out.write("	 <div class=\"scroll-sidebar\">\r\n");
      out.write("                <!-- Sidebar navigation-->\r\n");
      out.write("	<nav class=\"sidebar-nav\">\r\n");
      out.write("		<ul id=\"sidebarnav\">\r\n");
      out.write("			<!-- User Profile-->\r\n");
      out.write("			<li class=\"sidebar-item pt-2\">\r\n");
      out.write("			    <a id=\"dashboard-link\" class=\"sidebar-link waves-effect waves-dark sidebar-link\" \r\n");
      out.write("			       href=\"#\" aria-expanded=\"false\">\r\n");
      out.write("			        <i class=\"far fa-clock\" aria-hidden=\"true\"></i>\r\n");
      out.write("			        <span class=\"hide-menu\" style=\"color:black;\">Dashboard</span>\r\n");
      out.write("			    </a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/profile.htm\"\r\n");
      out.write("				aria-expanded=\"false\"> <i class=\"fa fa-user\" aria-hidden=\"true\"></i>\r\n");
      out.write("					<span class=\"hide-menu\" style=\"color:black;\">Profile</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/password.htm\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-arrows-rotate mr-10\"></i> <span class=\"hide-menu\" style=\"color:black;\">Change Password</span>\r\n");
      out.write("			</a><li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/customer.htm\"\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-users\"></i> <span class=\"hide-menu\" style=\"color:black;\">Customers</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/movie.htm\"\r\n");
      out.write("				aria-expanded=\"false\"> <i class=\"fa-solid fa-film\"></i> <span\r\n");
      out.write("					class=\"hide-menu\" style=\"color:black;\">Movies</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/directors.htm\"\r\n");
      out.write("				aria-expanded=\"false\"> <i class=\"fa-solid fa-clapperboard\"></i> <span\r\n");
      out.write("					class=\"hide-menu\" style=\"color:black;\">Directors</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/actors.htm\"\r\n");
      out.write("				aria-expanded=\"false\"> <i class=\"fa-solid fa-theater-masks\"></i> <span\r\n");
      out.write("					class=\"hide-menu\" style=\"color:black;\">Actors</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/seat.htm\"\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-ticket-simple\"></i> <span class=\"hide-menu\" style=\"color:black;\">Seat Types</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\">\r\n");
      out.write("			    <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"http://localhost:9999/DoAnWebCinema/admin/order.htm?filter=today\" aria-expanded=\"false\">\r\n");
      out.write("			        <i class=\"fa-solid fa-bookmark\"></i> <span class=\"hide-menu\" style=\"color:black;\">Booked Tickets</span>\r\n");
      out.write("			    </a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/room.htm\"\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-house-chimney\"></i> <span class=\"hide-menu\" style=\"color:black;\">Rooms</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/showtimes.htm\" aria-expanded=\"false\"> <i class=\"fa-solid fa-calendar-days\"></i><span \r\n");
      out.write("						class=\"hide-menu\" style=\"color:black;\">Showtimes</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/admin/type.htm\" aria-expanded=\"false\"> <i class=\"fa-solid fa-align-center\"></i> <span \r\n");
      out.write("						class=\"hide-menu\" style=\"color:black;\">Genres</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/login.htm\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-arrow-right-from-bracket\"></i> <span\r\n");
      out.write("					class=\"hide-menu\" style=\"color:black;\">Logout</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- End Sidebar navigation -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Sidebar scroll-->\r\n");
      out.write("</aside>\r\n");
      out.write("<script>\r\n");
      out.write("    const currentDate = new Date();\r\n");
      out.write("    const month = currentDate.getMonth() + 1;\r\n");
      out.write("    const year = currentDate.getFullYear();\r\n");
      out.write("    const dashboardLink = document.getElementById(\"dashboard-link\");\r\n");
      out.write("    dashboardLink.href = 'http://localhost:9999/DoAnWebCinema/admin/dashboard.htm?month=' +  month + '&year=' + year;\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-wrapper\" style=\"min-height: 250px;\">\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"page-breadcrumb bg-white\">\r\n");
      out.write("                <div class=\"row align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("                        <h4 class=\"page-title\">Khách Hàng</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.col-lg-12 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Start Page Content -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-12\">\r\n");
      out.write("                        <div class=\"white-box\">\r\n");
      out.write("                            <div class=\"box-header\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <h3 class=\"box-title\">Customer List</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"btn-add-e\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                    <button class=\"button-header1-e\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                        data-bs-target=\"#add-employee\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-circle-exclamation\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                            data-bs-target=\"#add-employee\"></i>\r\n");
      out.write("                                        Add\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("\r\n");
      out.write("                                <table class=\"table table-striped table-hover\" id=\"sortTable\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th class=\"border-top-0\">No.</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Customer ID</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Full Name</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Phone Number</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Gender</th>\r\n");
      out.write("                                            <th class=\"border-top-0\">Actions</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- Popup model add employee  -->\r\n");
      out.write("                            <div class=\"modal fade\" id=\"add-employee\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("                                <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("                                    <div class=\"modal-content\">\r\n");
      out.write("                                        <div class=\"modal-header\">\r\n");
      out.write("                                            <h4 class=\"modal-title\" id=\"myCenterModalLabel\">Add New Customer</h4>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\r\n");
      out.write("                                                aria-label=\"Close\"></button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"modal-body\">\r\n");
      out.write("                                            <!-- <div class=\"container tm-mt-big tm-mb-big h-100 align-items-center justify-content-center\"> -->\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <!-- <div class=\"col-12\"> -->\r\n");
      out.write("                                                <div class=\"tm-bg-primary-dark tm-block tm-block-h-auto\">\r\n");
      out.write("                                                    <div class=\"row tm-edit-product-row\">\r\n");
      out.write("                                                        <!-- <div class=\"col-12\"> -->\r\n");
      out.write("                                                        <!-- <div class=\"header-info\">\r\n");
      out.write("                                                    <!-- <h3 class=\"header-name-info\">Thông Tin Nhân Viên</h3> \r\n");
      out.write("                                                </div> -->\r\n");
      out.write("                                                        <form class=\"contener1-fix\">\r\n");
      out.write("                                                            <div class=\"body-full-fix\">\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"body-fix\">\r\n");
      out.write("                                                                    <div class=\"body-right-fix\">\r\n");
      out.write("                                                                        <div class=\"photo-fix\">\r\n");
      out.write("                                                                            <img src=\"http://localhost:9999/DoAnWebCinema/images/user.gif\" alt=\"user\" style=\"width: 200px;\"/>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                                        <div class=\"btn-fix\">\r\n");
      out.write("                                                                            <button class=\"button-ma-fix\">Add photo</button>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"body-right-detail-info-fix\">\r\n");
      out.write("                                                                            <p class=\"detail-info-top-left-fix\">Status:</p>\r\n");
      out.write("                                                                            <div id=\"buttons-fix\">\r\n");
      out.write("                                                                                <a href=\"#\"\r\n");
      out.write("                                                                                    class=\"btn-f btn-solid-f\">Active</a>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                    <div class=\"body-left-fix\">\r\n");
      out.write("                                                                        <div class=\"detail-info-fix\">\r\n");
      out.write("                                                                            <p class=\"detail-info-top-fix\">Full Name\r\n");
      out.write("                                                                            </p>\r\n");
      out.write("                                                                            <input\r\n");
      out.write("                                                                                class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"detail-info-fix\">\r\n");
      out.write("                                                                            <p class=\"detail-info-top-fix\">Email</p>\r\n");
      out.write("                                                                            <input\r\n");
      out.write("                                                                                class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"detail-info-fix\">\r\n");
      out.write("                                                                            <p class=\"detail-info-top-fix\">Phone</p>\r\n");
      out.write("                                                                            <input\r\n");
      out.write("                                                                                class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"detail-info-fix\">\r\n");
      out.write("                                                                            <p class=\"detail-info-top-fix\">Address</p>\r\n");
      out.write("                                                                            <input\r\n");
      out.write("                                                                                class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"same-fix\">\r\n");
      out.write("                                                                            <div class=\"detail-info-fix-left\">\r\n");
      out.write("                                                                                <p class=\"detail-info-top-fix\">Date of Birth\r\n");
      out.write("                                                                                </p>\r\n");
      out.write("                                                                                <form class=\"input-date\">\r\n");
      out.write("                                                                                    <input type=\"date\" name=\"\" id=\"\"\r\n");
      out.write("                                                                                        class=\"input-name-fix\">\r\n");
      out.write("                                                                                </form>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                            <div class=\"detail-info-fix-right\">\r\n");
      out.write("                                                                                <p class=\"detail-info-top-fix\">Gender\r\n");
      out.write("                                                                                </p>\r\n");
      out.write("                                                                                <div class=\"input-fix\">\r\n");
      out.write("                                                                                    <input type=\"radio\" name=\"\" id=\"\">Female\r\n");
      out.write("                                                                                    <input type=\"radio\" name=\"\"\r\n");
      out.write("                                                                                        id=\"\">Male\r\n");
      out.write("                                                                                </div>\r\n");
      out.write("                                                                            </div>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"body-botton-fix\">\r\n");
      out.write("                                                                    <button class=\"button-fix-f\">Save</button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              <!-- Popup info employee -->\r\n");
      out.write("<!-- Popup info customer -->\r\n");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Popup fix employee -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"fix-employee\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h4 class=\"modal-title\" id=\"myCenterModalLabel\">Chỉnh Sửa Nhân Viên</h4>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <!-- <div class=\"container tm-mt-big tm-mb-big h-100 align-items-center justify-content-center\"> -->\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <!-- <div class=\"col-12\"> -->\r\n");
      out.write("                        <div class=\"tm-bg-primary-dark tm-block tm-block-h-auto\">\r\n");
      out.write("                            <div class=\"row tm-edit-product-row\">\r\n");
      out.write("                                <!-- <div class=\"col-12\"> -->\r\n");
      out.write("                                <!-- <div class=\"header-info\">\r\n");
      out.write("                                                    <!-- <h3 class=\"header-name-info\">Thông Tin Nhân Viên</h3> \r\n");
      out.write("                                                </div> -->\r\n");
      out.write("                                <form class=\"contener1-fix\">\r\n");
      out.write("                                    <div class=\"body-full-fix\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"body-fix\">\r\n");
      out.write("                                            <div class=\"body-right-fix\">\r\n");
      out.write("                                                <div class=\"photo-fix\">\r\n");
      out.write("                                                    <i class=\"fa-solid fa-file-image\"\r\n");
      out.write("                                                        onclick=\"document.getElementById('fileIput').click();\"></i>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"btn-fix\">\r\n");
      out.write("                                                    <button class=\"button-ma-fix\">Sửa Ảnh</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"body-right-detail-info-fix\">\r\n");
      out.write("                                                    <p class=\"detail-info-top-left-fix\">Trạng Thái:</p>\r\n");
      out.write("                                                    <div id=\"buttons-fix\">\r\n");
      out.write("                                                        <a href=\"#\" class=\"btn-f btn-solid-f\">Hoạt Động</a>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"body-left-fix\">\r\n");
      out.write("                                                <li class=\"tieude-fix\">\r\n");
      out.write("                                                    <span class=\"chitiet-left-fix\">Mã Nhân Viên:</span>\r\n");
      out.write("                                                    <span class=\"chitiet-fix\">1001</span>\r\n");
      out.write("\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <div class=\"detail-info-fix\">\r\n");
      out.write("                                                    <p class=\"detail-info-top-fix\">Tên Nhân Viên</p>\r\n");
      out.write("                                                    <input class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"detail-info-fix\">\r\n");
      out.write("                                                    <p class=\"detail-info-top-fix\">CMND</p>\r\n");
      out.write("                                                    <input class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"detail-info-fix\">\r\n");
      out.write("                                                    <p class=\"detail-info-top-fix\">SĐT</p>\r\n");
      out.write("                                                    <input class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"detail-info-fix\">\r\n");
      out.write("                                                    <p class=\"detail-info-top-fix\">Địa Chỉ</p>\r\n");
      out.write("                                                    <input class=\"detail-info-buton-fix\"></input>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"same-fix\">\r\n");
      out.write("                                                    <div class=\"detail-info-fix-left\">\r\n");
      out.write("                                                        <p class=\"detail-info-top-fix\">Ngày Sinh</p>\r\n");
      out.write("                                                        <form class=\"input-date\">\r\n");
      out.write("                                                            <input type=\"date\" name=\"\" id=\"\" class=\"input-name-fix\">\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"detail-info-fix-right\">\r\n");
      out.write("                                                        <p class=\"detail-info-top-fix\">Giới Tính</p>\r\n");
      out.write("                                                        <div class=\"input-fix\">\r\n");
      out.write("                                                            <input type=\"radio\" name=\"\" id=\"\">Nữ\r\n");
      out.write("                                                            <input type=\"radio\" name=\"\" id=\"\">Nam\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"body-botton-fix\">\r\n");
      out.write("                                            <button class=\"button-fix-f\">Thêm Mới</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- footer -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End footer -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Page wrapper  -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("  \r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Wrapper -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- All Jquery -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <script>\r\n");
      out.write("        $('#sortTable').DataTable();\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/app-style-switcher.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("    <!--Wave Effects -->\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/waves.js\"></script>\r\n");
      out.write("    <!--Menu sidebar -->\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/sidebarmenu.js\"></script>\r\n");
      out.write("    <!--Custom JavaScript -->\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/custom.js\"></script>\r\n");
      out.write("    <!--This page JavaScript -->\r\n");
      out.write("    <!--chartis chart-->\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/chartist.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/dashboard1.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/admin/customer.jsp(229,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("s");
      // /WEB-INF/views/admin/customer.jsp(229,36) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/customer.jsp(229,36) '${kh}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${kh}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/admin/customer.jsp(229,36) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                        <tr>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loop.index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maKH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.tenKH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.soDT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                            ");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                                            <td>\r\n");
            out.write("\r\n");
            out.write("                                                <a href=\"#\">\r\n");
            out.write("                                                    <button class=\"button\" data-bs-toggle=\"modal\"\r\n");
            out.write("                                                        data-bs-target=\"#show");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maKH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                                        <i class=\"fa-solid fa-circle-exclamation\"></i>\r\n");
            out.write("                                                    </button>\r\n");
            out.write("                                                </a>\r\n");
            out.write("                                               \r\n");
            out.write("                                            </td>\r\n");
            out.write("                                        </tr>                            \r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                                            	");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/admin/customer.jsp(236,45) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.gioiTinh == false}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            		<td>Nữ</td>\r\n");
          out.write("                                            	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/admin/customer.jsp(239,45) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.gioiTinh == true}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                            		<td>Nam</td>\r\n");
          out.write("                                            	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/admin/customer.jsp(366,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("s");
      // /WEB-INF/views/admin/customer.jsp(366,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/customer.jsp(366,0) '${kh}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${kh}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <div class=\"modal fade\" id=\"show");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
            out.write("        <div class=\"modal-dialog modal-lg modal-dialog-centered\">\r\n");
            out.write("            <div class=\"modal-content\">\r\n");
            out.write("                <!-- Modal Header -->\r\n");
            out.write("                <div class=\"modal-header bg-primary text-white\">\r\n");
            out.write("                    <h4 class=\"modal-title\">Customer Information</h4>\r\n");
            out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
            out.write("                </div>\r\n");
            out.write("                <!-- Modal Body -->\r\n");
            out.write("                <div class=\"modal-body\">\r\n");
            out.write("                    <div class=\"container-fluid\">\r\n");
            out.write("                        <div class=\"row\">\r\n");
            out.write("                            <!-- Customer Image and Status -->\r\n");
            out.write("                            <div class=\"col-md-4 text-center\">\r\n");
            out.write("                                <img src=\"http://localhost:9999/DoAnWebCinema/images/user.gif\" alt=\"user\" class=\"img-fluid rounded-circle mb-3\" style=\"width: 150px; height: 150px; object-fit: cover;\"/>\r\n");
            out.write("                                <button class=\"btn btn-outline-primary mb-3\">Customer ID: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</button>\r\n");
            out.write("                                <p class=\"status text-success\">Active</p>\r\n");
            out.write("                            </div>\r\n");
            out.write("                            \r\n");
            out.write("                            <!-- Detailed Customer Information -->\r\n");
            out.write("                            <div class=\"col-md-8\">\r\n");
            out.write("                                <div class=\"row\">\r\n");
            out.write("                                    <div class=\"col-12\">\r\n");
            out.write("                                        <div class=\"info-box\">\r\n");
            out.write("                                            <p class=\"label\">Customer Name</p>\r\n");
            out.write("                                            <h6 class=\"info-detail\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.tenKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"col-12\">\r\n");
            out.write("                                        <div class=\"info-box\">\r\n");
            out.write("                                            <p class=\"label\">Phone Number</p>\r\n");
            out.write("                                            <h6 class=\"info-detail\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.soDT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"col-6\">\r\n");
            out.write("                                        <div class=\"info-box\">\r\n");
            out.write("                                            <p class=\"label\">Date of Birth</p>\r\n");
            out.write("                                            <h6 class=\"info-detail\">");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</h6>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"col-6\">\r\n");
            out.write("                                        <div class=\"info-box\">\r\n");
            out.write("                                            <p class=\"label\">Gender</p>\r\n");
            out.write("                                            <h6 class=\"info-detail\">\r\n");
            out.write("                                                ");
            if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("                                            </h6>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"col-12\">\r\n");
            out.write("                                        <div class=\"info-box\">\r\n");
            out.write("                                            <p class=\"label\">Address</p>\r\n");
            out.write("                                            <h6 class=\"info-detail\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.diaChi}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </div>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("        </div>\r\n");
            out.write("    </div>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/admin/customer.jsp(404,68) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.ngaySinh}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/admin/customer.jsp(404,68) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("MM-dd-yyyy");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                                    ");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                                                    ");
          if (_jspx_meth_c_005fwhen_005f3(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("                                                ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/admin/customer.jsp(412,52) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.gioiTinh == false}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("Female");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f3 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f3_reused = false;
    try {
      _jspx_th_c_005fwhen_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/admin/customer.jsp(413,52) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.gioiTinh == true}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f3 = _jspx_th_c_005fwhen_005f3.doStartTag();
      if (_jspx_eval_c_005fwhen_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("Male");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f3);
      _jspx_th_c_005fwhen_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f3_reused);
    }
    return false;
  }
}
