/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2025-01-08 07:08:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lienhe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/jstl-impl.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1719237896340L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>TỨ TRỤ CINEMA</title>\r\n");
      out.write("<link rel=\"icon\" type=\"images/png\" href=\"images/logocinema.png\">\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/global.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/index.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Rajdhani&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 	Phần đầu -->\r\n");
      out.write("	<section id=\"top\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			 <div class=\"row top_1\">\r\n");
      out.write("			 	<div class=\"col-md-3\">\r\n");
      out.write(" 				   <div class=\"top_1l pt-1\">\r\n");
      out.write("		    			<h3 class=\"mb-0\"><a class=\"text-white\" href=\"\"><i class=\"fa fa-video-camera col_red me-1\"></i>Tứ Trụ Cinema</a></h3>\r\n");
      out.write("		   			</div>\r\n");
      out.write("			 	</div>\r\n");
      out.write("			 	<div class=\"col-md-5\">\r\n");
      out.write("   	 				<div class=\"top_1m\">\r\n");
      out.write("    					<form class=\"col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3\" action=\"/DoAnWebCinema/search.htm\">\r\n");
      out.write("							<input type=\"search\" class=\"form-control form-control-dark\" placeholder=\"Tìm kiếm...\" aria-label=\"Search\" name=\"search\">\r\n");
      out.write("						</form>\r\n");
      out.write("        			</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("				    <div class=\"top_1r text-end mt-1\">\r\n");
      out.write("				        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("			 </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- 	Phần Menu -->\r\n");
      out.write("	<section id=\"header\">\r\n");
      out.write("		<nav class=\"navbar navbar-expand-md navbar-light\" id=\"navbar_sticky\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<a class=\"navbar-brand text-white fw-bold\" href=\"\"><i class=\"fa fa-video-camera col_red me-1\"></i>TU TRU CINEMA</a>\r\n");
      out.write("				    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("				    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			    </button>\r\n");
      out.write("    			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("					<ul class=\"navbar-nav mb-0\">\r\n");
      out.write("			        	<li class=\"nav-item\">\r\n");
      out.write("			          		<a class=\"nav-link active\" aria-current=\"page\" href=\"trangchu.htm\">Home</a>\r\n");
      out.write("			        	</li>\r\n");
      out.write("			     		<li class=\"nav-item\">\r\n");
      out.write("			          		<a id=\"dat-ve-link\" class=\"nav-link\" href=\"#\">Book Now</a>\r\n");
      out.write("			        	</li>\r\n");
      out.write("			        	<li class=\"nav-item dropdown\">\r\n");
      out.write("			          		<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Movie</a>\r\n");
      out.write("			          		<ul class=\"dropdown-menu drop_1\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("						    	<li><a class=\"dropdown-item\" href=\"phimsapchieu.htm?tab=home\">Now Showing</a></li>\r\n");
      out.write("						    	<li><a class=\"dropdown-item border-0\" href=\"phimsapchieu.htm?tab=profile\">Coming Soon</a></li>\r\n");
      out.write("			          		</ul>\r\n");
      out.write("			        	</li>\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("			          		<a class=\"nav-link\" href=\"gioithieu.htm\">About Us</a>\r\n");
      out.write("		        		</li>\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("			          		<a class=\"nav-link\" href=\"lienhe.htm\">Contact</a>\r\n");
      out.write("			        	</li>\r\n");
      out.write("			      	</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("<section id=\"center\" class=\"center_o pt-2 pb-2\">\r\n");
      out.write("		<div class=\"container-xl\">\r\n");
      out.write("			<div class=\"row center_o1\">\r\n");
      out.write("				<div class=\"col-md-5\">\r\n");
      out.write("					<div class=\"center_o1l\">\r\n");
      out.write("						<h2 class=\"mb-0\">Contact</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-7\">\r\n");
      out.write("					<div class=\"center_o1r text-end\">\r\n");
      out.write("						<h6 class=\"mb-0 col_red\">\r\n");
      out.write("							<a href=\"#\">Home</a> <span class=\"me-2 ms-2 text-light\"><i\r\n");
      out.write("								class=\"fa fa-caret-right align-middle\"></i></span> Contact\r\n");
      out.write("						</h6>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	<section id=\"contact\" class=\"pt-4 pb-4 bg_grey\">\r\n");
      out.write("		<div class=\"container-xl\">\r\n");
      out.write("			<div class=\"row contact_1 bg_dark  pt-5 pb-5\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"contact_1i row\">\r\n");
      out.write("						<div class=\"col-md-2 col-2\">\r\n");
      out.write("							<div class=\"contact_1il\">\r\n");
      out.write("								<span class=\"col_red fs-3\"><i class=\"fa fa-map-marker\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-10 col-10\">\r\n");
      out.write("							<div class=\"contact_1ir\">\r\n");
      out.write("								<h5 class=\"col_red\">Location</h5>\r\n");
      out.write("								<p class=\"mb-0\">\r\n");
      out.write("97 Man Thiện St., Hiệp Phú, Thủ Đức, Ho Chi Minh City, Vietnam</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"contact_1i row\">\r\n");
      out.write("						<div class=\"col-md-2 col-2\">\r\n");
      out.write("							<div class=\"contact_1il\">\r\n");
      out.write("								<span class=\"col_red fs-3\"><i class=\"fa fa-clock-o\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-10 col-10\">\r\n");
      out.write("							<div class=\"contact_1ir\">\r\n");
      out.write("								<h5 class=\"col_red\">Operating Hours</h5>\r\n");
      out.write("								<p class=\"mb-0\">8:00 - 23:00</p>\r\n");
      out.write("								<p class=\"mb-0\">All days, including holidays and Tet</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"contact_1i row\">\r\n");
      out.write("						<div class=\"col-md-2 col-2\">\r\n");
      out.write("							<div class=\"contact_1il\">\r\n");
      out.write("								<span class=\"col_red fs-3\"><i class=\"fa fa-envelope\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-10 col-10\">\r\n");
      out.write("							<div class=\"contact_1ir\">\r\n");
      out.write("								<h5 class=\"col_red\">E-mail</h5>\r\n");
      out.write("								<p class=\"mb-0\">tutrucinema@gmail.com</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"contact_1i row\">\r\n");
      out.write("						<div class=\"col-md-2 col-2\">\r\n");
      out.write("							<div class=\"contact_1il\">\r\n");
      out.write("								<span class=\"col_red fs-3\"><i class=\"fa fa-phone\"></i></span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-10 col-10\">\r\n");
      out.write("							<div class=\"contact_1ir\">\r\n");
      out.write("								<h5 class=\"col_red\">Hotline</h5>\r\n");
      out.write("								<p class=\"mb-0\">1900 0099</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row contact_2 mt-4\">\r\n");
      out.write("				<div class=\"col-md-3\">\r\n");
      out.write("					<div class=\"contact_2r\">\r\n");
      out.write("						<h5 class=\"mb-3\">Headquarters</h5>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fa fa-car col_red me-1\"></i>\r\n");
      out.write("97 Man Thiện St., Hiệp Phú, Thủ Đức, Ho Chi Minh City, Vietnam\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fa fa-phone col_red me-1\"></i> 1900 0099\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fa fa-globe col_red me-1\"></i> <a href=\"#\">info@gmail.com</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							<i class=\"fa fa-envelope col_red me-1\"></i> <a href=\"#\">tutrucinema@gmail.com</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<h5 class=\"mb-3 mt-4\">Office Hours</h5>\r\n");
      out.write("						<p>\r\n");
      out.write("							Monday – Friday: <span class=\"fw-bold text-white\">8:00 -\r\n");
      out.write("								22:00</span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							Saturday : <span class=\"fw-bold text-white\">8:00 to 13:00</span>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>\r\n");
      out.write("							Sunday : <span class=\"fw-bold text-white\">Closed</span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-9\">\r\n");
      out.write("					<div class=\"contact_2l row\">\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<h4>CONTACT</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"contact_2l1 mt-3 row\">\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<div class=\"contact_2l1i\">\r\n");
      out.write("								<input class=\"form-control\" placeholder=\"Full Name*\" type=\"text\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-md-6\">\r\n");
      out.write("							<div class=\"contact_2l1i\">\r\n");
      out.write("								<input class=\"form-control\" placeholder=\"Email*\" type=\"text\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"contact_2l1 mt-3 row\">\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<div class=\"contact_2l1i\">\r\n");
      out.write("								<textarea placeholder=\"Content to contact usc\"\r\n");
      out.write("									class=\"form-control form_text\"></textarea>\r\n");
      out.write("								<h6 class=\"mt-3 mb-0\">\r\n");
      out.write("									<a class=\"button\" href=\"#\">Send</a>\r\n");
      out.write("								</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row contact_3 mt-4\">\r\n");
      out.write("				<div class=\"col-md-12\">\r\n");
      out.write("					<iframe\r\n");
      out.write("						src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.520141589769!2d106.7840897748836!3d10.847986989305172!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752772b245dff1%3A0xb838977f3d419d!2sPosts%20and%20Telecommunications%20Institute%20of%20Technology%20HCM%20Branch!5e0!3m2!1sen!2s!4v1715764857608!5m2!1sen!2s\"\r\n");
      out.write("						height=\"450\" style=\"border: 0; width: 100%;\" allowfullscreen=\"\"></iframe>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section id=\"footer\">\r\n");
      out.write("		<div class=\"footer_m clearfix\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row footer_1\">\r\n");
      out.write("					<div class=\"col-md-4\">\r\n");
      out.write("						<div class=\"footer_1i\">\r\n");
      out.write("							<h3>\r\n");
      out.write("								<a class=\"text-white\" href=\"index.html\"><i\r\n");
      out.write("									class=\"fa fa-video-camera col_red me-1\"></i> <span\r\n");
      out.write("									class=\"col_red\">Contact</span></a>\r\n");
      out.write("							</h3>\r\n");
      out.write("							<p class=\"mt-3\">Tu Tru. Where Emotions Converge.</p>\r\n");
      out.write("							<h6 class=\"fw-normal\">\r\n");
      out.write("								<i class=\"fa fa-map-marker fs-5 align-middle col_red me-1\"></i>\r\n");
      out.write("97 Man Thiện St., Hiệp Phú, Thủ Đức, Ho Chi Minh City, Vietnam\r\n");
      out.write("							</h6>\r\n");
      out.write("							<h6 class=\"fw-normal mt-3\">\r\n");
      out.write("								<i class=\"fa fa-envelope fs-5 align-middle col_red me-1\"></i>\r\n");
      out.write("								tutrucinema@gmail.com\r\n");
      out.write("							</h6>\r\n");
      out.write("							<h6 class=\"fw-normal mt-3 mb-0\">\r\n");
      out.write("								<i class=\"fa fa-phone fs-5 align-middle col_red me-1\"></i> 1900\r\n");
      out.write("								0099\r\n");
      out.write("							</h6>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4\">\r\n");
      out.write("						<div class=\"footer_1i\">\r\n");
      out.write("							<h4>\r\n");
      out.write("								<span class=\"col_red\">Newsletter</span>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<p class=\"mt-3\">\r\n");
      out.write("Subscribe to our newsletter to receive the latest news and updates from us.</p>\r\n");
      out.write("							<div class=\"input-group\">\r\n");
      out.write("								<input type=\"text\" class=\"form-control bg-black\"\r\n");
      out.write("									placeholder=\"Email\"> <span class=\"input-group-btn\">\r\n");
      out.write("									<button class=\"btn btn text-white bg_red rounded-0 border-0\"\r\n");
      out.write("										type=\"button\">Sign up</button>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-4\">\r\n");
      out.write("						<div class=\"footer_1i text-center\">\r\n");
      out.write("							<h4 class=\"mb-4\">\r\n");
      out.write("								<span class=\"col_red\">Connect with Us</span>\r\n");
      out.write("							</h4>\r\n");
      out.write("							<div class=\"footer_1i1\">\r\n");
      out.write("								<ul class=\"social-network social-square mb-0 mt-4\">\r\n");
      out.write("									<li class=\"\"><a\r\n");
      out.write("										href=\"https://www.facebook.com/profile.php?id=100018102729044\"><img\r\n");
      out.write("											src=\"images/facebook.png\" height=\"50\" title=\"Facebook\"\r\n");
      out.write("											alt=\"Facebook\"></a></li>\r\n");
      out.write("									<li class=\"\"><a href=\"\"><img\r\n");
      out.write("											src=\"images/instagram.png\" height=\"50\" title=\"Instagram\"\r\n");
      out.write("											alt=\"Instagram\"></a></li>\r\n");
      out.write("									<li class=\"\"><a href=\"\"><img\r\n");
      out.write("											src=\"images/tiktok.png\" height=\"50\" title=\"Tiktok\"\r\n");
      out.write("											alt=\"Tiktok\"></a></li>\r\n");
      out.write("									<li class=\"\"><a href=\"\"><img\r\n");
      out.write("											src=\"images/youtube.png\" height=\"50\" title=\"Youtube\"\r\n");
      out.write("											alt=\"Youtube\"></a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"footer_1i1 mt-3\">\r\n");
      out.write("								<a\r\n");
      out.write("									href=\"http://online.gov.vn/HomePage/CustomWebsiteDisplay.aspx?DocId=30278\"\r\n");
      out.write("									target=\"_blank\"> <img src=\"images/bocongthuong.png\"\r\n");
      out.write("									height=\"80\" alt=\"abc\">\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section id=\"footer_b\" class=\"pt-3 pb-3 bg_grey\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row footer_1 text-center\">\r\n");
      out.write("				<p class=\"mb-0\">© 2024 Tu Tru Cinema. All Rights Reserved</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("window.onscroll = function() {myFunction()};\r\n");
      out.write("\r\n");
      out.write("var navbar_sticky = document.getElementById(\"navbar_sticky\");\r\n");
      out.write("var sticky = navbar_sticky.offsetTop;\r\n");
      out.write("var navbar_height = document.querySelector('.navbar').offsetHeight;\r\n");
      out.write("\r\n");
      out.write("function myFunction() {\r\n");
      out.write("  if (window.pageYOffset >= sticky + navbar_height) {\r\n");
      out.write("    navbar_sticky.classList.add(\"sticky\")\r\n");
      out.write("	document.body.style.paddingTop = navbar_height + 'px';\r\n");
      out.write("  } else {\r\n");
      out.write("    navbar_sticky.classList.remove(\"sticky\");\r\n");
      out.write("	document.body.style.paddingTop = '0'\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    // Lấy ngày hiện tại\r\n");
      out.write("    var curDate = new Date();\r\n");
      out.write("    var date = curDate.getDate();\r\n");
      out.write("    var month = curDate.getMonth() + 1; // Tháng bắt đầu từ 0\r\n");
      out.write("    var year = curDate.getFullYear();\r\n");
      out.write("\r\n");
      out.write("    // Định dạng ngày theo định dạng yyyy-mm-dd\r\n");
      out.write("    var formattedDate = year + '-' + (month < 10 ? '0' + month : month) + '-' + (date < 10 ? '0' + date : date);\r\n");
      out.write("\r\n");
      out.write("    // Cập nhật liên kết href\r\n");
      out.write("    var link = document.getElementById('dat-ve-link');\r\n");
      out.write("    if (link) { // Kiểm tra xem phần tử có tồn tại không\r\n");
      out.write("        link.href = '/DoAnWebCinema/datve/' + formattedDate + '.htm?chinhanh=1';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/lienhe.jsp(44,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				                <p><i class=\"bi bi-person-circle\"></i><span> </span><a href=\"customer/account.htm\"><strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong></a></p>\r\n");
          out.write("				            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				                <div>\r\n");
          out.write("				                    <i class=\"bi bi-person-circle\"></i>\r\n");
          out.write("				                    <a href=\"login.htm\"><b>Login</b></a>\r\n");
          out.write("				                    <a href=\"register.htm\"><b>Sign Up</b></a>\r\n");
          out.write("				                </div>\r\n");
          out.write("				            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
