/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-11-21 12:58:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.staff;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class password_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/include/taglib.jsp", Long.valueOf(1719237896461L));
    _jspx_dependants.put("/WEB-INF/views/include/header_admin.jsp", Long.valueOf(1731599862053L));
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("/WEB-INF/views/include/aside_staff.jsp", Long.valueOf(1732193586369L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1719237896436L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1719237896340L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Đặt Mật Khẩu</title>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Ample lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Ample admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Ample Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/ample-admin-lite/\" />\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"http://localhost:9999/DoAnWebCinema/imgs/favicon.png\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"http://localhost:9999/DoAnWebCinema/css/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/chartist-plugin-tooltip.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\" integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link href=\"http://localhost:9999/DoAnWebCinema/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://localhost:9999/DoAnWebCinema/css/employee.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/detail-test.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/fix-test.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- <div class=\"container\" style=\"width:100%\";>\r\n");
      out.write("<h2> Bootstrap Sort Table </h2> -->\r\n");
      out.write("<div class=\"alert-flag\" aType='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("		aMessage=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\r\n");
      out.write("<div class=\"preloader\">\r\n");
      out.write("    <div class=\"lds-ripple\">\r\n");
      out.write("        <div class=\"lds-pos\"></div>\r\n");
      out.write("        <div class=\"lds-pos\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ============================================================== -->\r\n");
      out.write("<!-- Main wrapper - style you can find in pages.scss -->\r\n");
      out.write("<!-- ============================================================== -->\r\n");
      out.write("<div id=\"main-wrapper\" data-layout=\"vertical\" data-navbarbg=\"skin5\" data-sidebartype=\"full\"\r\n");
      out.write("    data-sidebar-position=\"absolute\" data-header-position=\"absolute\" data-boxed-layout=\"full\">\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Topbar header - style you can find in pages.scss -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    	#navbarSupportedContent{\r\n");
      out.write("    		background-color: #2f323e;\r\n");
      out.write("    	}\r\n");
      out.write("    .logo-icon {\r\n");
      out.write("        width: 40px;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .brand-text {\r\n");
      out.write("        font-size: 1.2rem;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #e50914;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-brand:hover .brand-text {\r\n");
      out.write("        color: #f15b5b;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 576px) {\r\n");
      out.write("        .navbar {\r\n");
      out.write("            padding: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .brand-text {\r\n");
      out.write("            font-size: 1.25rem;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("        <header class=\"topbar\" data-navbarbg=\"skin5\">\r\n");
      out.write("            <nav class=\"navbar top-navbar navbar-expand-md navbar-dark\">\r\n");
      out.write("                <div class=\"navbar-header\" data-logobg=\"skin6\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("					<nav class=\"navbar navbar-expand-lg navbar-light\">\r\n");
      out.write("					    <div class=\"container\">\r\n");
      out.write("					        <!-- Brand and logo -->\r\n");
      out.write("					        <a class=\"navbar-brand d-flex align-items-center\" href=\"http://localhost:9999/DoAnWebCinema/admin/dashboard.htm\">\r\n");
      out.write("					            <img src=\"http://localhost:9999/DoAnWebCinema/images/logocinema.png\" alt=\"Tứ Trụ Cinema Logo\" class=\"logo-icon\" />\r\n");
      out.write("					            <span class=\"brand-text\"><b>Tứ Trụ Cinema</b></span>\r\n");
      out.write("					        </a>\r\n");
      out.write("					    </div>\r\n");
      out.write("					</nav>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <a class=\"nav-toggler waves-effect waves-light text-dark d-block d-md-none\"\r\n");
      out.write("                        href=\"javascript:void(0)\"><i class=\"ti-menu ti-close\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" id=\"navbarSupportedContent\" data-navbarbg=\"skin5\">\r\n");
      out.write("                    <ul class=\"navbar-nav d-none d-md-block d-lg-none\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-toggler nav-link waves-effect waves-light text-white\"\r\n");
      out.write("                                href=\"javascript:void(0)\"><i class=\"ti-menu ti-close\"></i></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Right side toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto d-flex align-items-center\">\r\n");
      out.write("	<li class=\"ms-auto\">\r\n");
      out.write("    <p class=\"app-search d-none d-md-block me-3\" style=\"color:white;\"><b><i>Chi nhánh ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.chiNhanh.tenChiNhanh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</i></b></p>\r\n");
      out.write("</li>\r\n");
      out.write("\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- Search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li class=\" in\">\r\n");
      out.write("                            <form role=\"search\" class=\"app-search d-none d-md-block me-3\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Tìm kiếm...\" class=\"form-control mt-0\">\r\n");
      out.write("                                <a href=\"\" class=\"active\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"profile-pic\" href=\"#\">\r\n");
      out.write("                                <img src=\"http://localhost:9999/DoAnWebCinema/images/user.gif\" alt=\"user-img\" width=\"36\"\r\n");
      out.write("                                    class=\"img-circle\"><span class=\"text-white font-medium\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenNV}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Topbar header -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.selected{\r\n");
      out.write("		background-color: #fff;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<aside class=\"left-sidebar\" data-sidebarbg=\"skin6\">\r\n");
      out.write("	<!-- Sidebar scroll-->\r\n");
      out.write("	 <div class=\"scroll-sidebar\">\r\n");
      out.write("                <!-- Sidebar navigation-->\r\n");
      out.write("	<nav class=\"sidebar-nav\">\r\n");
      out.write("		<ul id=\"sidebarnav\">\r\n");
      out.write("			<!-- User Profile-->\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/staff/profile.htm\"\r\n");
      out.write("				aria-expanded=\"false\"> <i class=\"fa fa-user\" aria-hidden=\"true\"></i>\r\n");
      out.write("					<span class=\"hide-menu\">Hồ Sơ</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/staff/password.htm\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-arrows-rotate mr-10\"></i> <span class=\"hide-menu\">Đổi Mật Khẩu</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/staff/order.htm\"\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-ticket-simple\"></i> <span class=\"hide-menu\">Đặt Vé</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/staff/support.htm\"\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-house-chimney\"></i> <span class=\"hide-menu\">Hỗ trợ khách hàng</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("			<li class=\"sidebar-item\"><a\r\n");
      out.write("				class=\"sidebar-link waves-effect waves-dark sidebar-link\"\r\n");
      out.write("				href=\"http://localhost:9999/DoAnWebCinema/login.htm\" aria-expanded=\"false\"> <i\r\n");
      out.write("					class=\"fa-solid fa-arrow-right-from-bracket\"></i> <span\r\n");
      out.write("					class=\"hide-menu\">Đăng Xuất</span>\r\n");
      out.write("			</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- End Sidebar navigation -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- End Sidebar scroll-->\r\n");
      out.write("</aside>\r\n");
      out.write(" \r\n");
      out.write("	\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Page wrapper  -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div class=\"page-wrapper\" style=\"min-height: 250px;\">\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Bread crumb and right sidebar toggle -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-breadcrumb bg-white\">\r\n");
      out.write("				<div class=\"row align-items-center\">\r\n");
      out.write("					<div class=\"col-lg-3 col-md-4 col-sm-4 col-xs-12\">\r\n");
      out.write("						<h4 class=\"page-title\">Đổi Mật Khẩu</h4>\r\n");
      out.write("						");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- /.col-lg-12 -->\r\n");
      out.write("			</div>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Bread crumb and right sidebar toggle -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Container fluid  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Start Page Content -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-12\">\r\n");
      out.write("                    <div class=\"white-box\">\r\n");
      out.write("                        \r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                <div class=\"ten\">\r\n");
      out.write("                                                <form class=\"col-4 mx-auto pt-5 card\" method=\"post\" action=\"/DoAnWebCinema/admin/password.htm\">\r\n");
      out.write("                                                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                            <label for=\"input-current-password\"><b>Mật khẩu hiện tại</b></label>\r\n");
      out.write("                                                            <input type=\"password\" name=\"oldPass\" class=\"form-control\"\r\n");
      out.write("                                                                id=\"input-current-password\" required/>\r\n");
      out.write("                                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message_o}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                            <label for=\"input-new-password\"><b>Mật khẩu mới</b></label>\r\n");
      out.write("                                                            <input type=\"password\" name=\"newPass\" class=\"form-control\"\r\n");
      out.write("                                                                id=\"input-new-password\" required/>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                            <label for=\"input-confirm-new-password\"><b>Xác nhận mật khẩu mới</b></label>\r\n");
      out.write("                                                            <input type=\"password\" name=\"confirmPass\"\r\n");
      out.write("                                                                class=\"form-control\" id=\"input-confirm-new-password\" required/>\r\n");
      out.write("                                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message_n}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"form-group col-12\">\r\n");
      out.write("                                                            <button type=\"submit\" name=\"btnpw\"\r\n");
      out.write("                                                                class=\"btn btn-primary col-12\" style=\"background-color: #0083f7; color: #fff; height: 35px; border: none00; border: none; border-radius: 5px;\">\r\n");
      out.write("                                                                Lưu thay đổi\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </form>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                    \r\n");
      out.write("                                \r\n");
      out.write("										\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("         \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>  \r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("        \r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- footer -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End footer -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Page wrapper  -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ============================================================== -->\r\n");
      out.write("<!-- End Wrapper -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- ============================================================== -->\r\n");
      out.write("<!-- ============================================================== -->\r\n");
      out.write("<!-- All Jquery -->\r\n");
      out.write("<!-- ============================================================== -->\r\n");
      out.write("<script>\r\n");
      out.write("$('#sortTable').DataTable();\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/jquery.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/app-style-switcher.js\"></script>\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/jquery.sparkline.min.js\"></script>\r\n");
      out.write("<!--Wave Effects -->\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/waves.js\"></script>\r\n");
      out.write("<!--Menu sidebar -->\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/sidebarmenu.js\"></script>\r\n");
      out.write("<!--Custom JavaScript -->\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/custom.js\"></script>\r\n");
      out.write("<!--This page JavaScript -->\r\n");
      out.write("<!--chartis chart-->\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/chartist.min.js\"></script>\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://localhost:9999/DoAnWebCinema/js/pages/dashboards/dashboard1.js\"></script>\r\n");
      out.write("	<script src=\" ");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		if ($(\".alert-flag\").attr(\"aType\")) {\r\n");
      out.write("			console.log(1)\r\n");
      out.write("			alertify.notify($(\".alert-flag\").attr(\"aMessage\"), $(\".alert-flag\").attr(\"aType\"), 5, function() { console.log('dismissed'); });\r\n");
      out.write("			alertify.set('notifier', 'position', 'top-right');\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/staff/password.jsp(34,33) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/alertify.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/staff/password.jsp(182,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/js/alertify.min.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
