/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2025-01-11 12:57:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class account_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1719237896436L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1719237896340L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Personal Information</title>\r\n");
      out.write("    <base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("        integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/fonts/fontawesome-pro-6.1.1-web/css/all.min.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" integrity=\"sha512-rqQltXRuHxtPWhktpAZxLHUVJ3Eombn3hvk9PHjV/N5DMUYnzKPC1i3ub0mEXgFzsaZNeJcoE0YHq0j/GFsdGg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <!-- Template CSS -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/main.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/alertify.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/account.css\">\r\n");
      out.write("   	<link href=\"http://localhost:9999/DoAnWebCinema/css/font-awesome.min.css\" rel=\"stylesheet\" >\r\n");
      out.write("	<link href=\"http://localhost:9999/DoAnWebCinema/css/global.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"http://localhost:9999/DoAnWebCinema/css/index.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"http://localhost:9999/DoAnWebCinema/css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Rajdhani&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("	<script src=\"http://localhost:9999/DoAnWebCinema/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.1/examples/headers/\">\r\n");
      out.write("    <style>\r\n");
      out.write("    	.bd-placeholder-img {\r\n");
      out.write("	        font-size: 1.125rem;\r\n");
      out.write("	        text-anchor: middle;\r\n");
      out.write("	        -webkit-user-select: none;\r\n");
      out.write("	        -moz-user-select: none;\r\n");
      out.write("	        user-select: none;\r\n");
      out.write("	      }\r\n");
      out.write("\r\n");
      out.write("    	@media (min-width: 768px) {\r\n");
      out.write("	    	.bd-placeholder-img-lg {\r\n");
      out.write("	        	font-size: 3.5rem;\r\n");
      out.write("	        }\r\n");
      out.write("	    }	   \r\n");
      out.write("	    \r\n");
      out.write("    </style>\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        #carousel-simple {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("         \r\n");
      out.write("    	.errors{\r\n");
      out.write("    		color: red;\r\n");
      out.write("    	}\r\n");
      out.write("    	.col-3 .text-center{\r\n");
      out.write("    		background: #088178;\r\n");
      out.write("    		color: #222222;\r\n");
      out.write("    	}\r\n");
      out.write("    	.dropdown:hover .dropdown-menu {\r\n");
      out.write("			display: block;\r\n");
      out.write("			margin-top: 0;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 	Phần đầu -->\r\n");
      out.write("<section id=\"top\">\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		 <div class=\"row top_1\">\r\n");
      out.write("		 	<div class=\"col-md-3\">\r\n");
      out.write("				   <div class=\"top_1l pt-1\">\r\n");
      out.write("	    			<h3 class=\"mb-0\"><a class=\"text-white\" href=\"\"><i class=\"fa fa-video-camera col_red me-1\"></i>Tứ Trụ Cinema</a></h3>\r\n");
      out.write("	   			</div>\r\n");
      out.write("		 	</div>\r\n");
      out.write("		 	<div class=\"col-md-5\">\r\n");
      out.write("  	 				<div class=\"top_1m\">\r\n");
      out.write("   					<form class=\"col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3\" action=\"/DoAnWebCinema/search.htm\">\r\n");
      out.write("						<input type=\"search\" class=\"form-control form-control-dark\" placeholder=\"Tìm kiếm...\" aria-label=\"Search\" name=\"search\">\r\n");
      out.write("					</form>\r\n");
      out.write("       			</div>\r\n");
      out.write("   			</div>\r\n");
      out.write("			<div class=\"col-md-4\">\r\n");
      out.write("			    <div class=\"top_1r text-end mt-1\">\r\n");
      out.write("			        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			    </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		 </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- 	Phần Menu -->\r\n");
      out.write("<section id=\"header\">\r\n");
      out.write("	<nav class=\"navbar navbar-expand-md navbar-light\" id=\"navbar_sticky\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand text-white fw-bold\" href=\"\"><i class=\"fa fa-video-camera col_red me-1\"></i>TU TRU CINEMA</a>\r\n");
      out.write("			    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		    </button>\r\n");
      out.write("   			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("				<ul class=\"navbar-nav mb-0\">\r\n");
      out.write("		        	<li class=\"nav-item\">\r\n");
      out.write("		          		<a class=\"nav-link active\" aria-current=\"page\" href=\"trangchu.htm\">Home</a>\r\n");
      out.write("		        	</li>\r\n");
      out.write("		     		<li class=\"nav-item\">\r\n");
      out.write("		          		<a id=\"dat-ve-link\" class=\"nav-link\" href=\"#\">Book Now</a>\r\n");
      out.write("		        	</li>\r\n");
      out.write("		        	<li class=\"nav-item dropdown\">\r\n");
      out.write("		          		<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Movie</a>\r\n");
      out.write("		          		<ul class=\"dropdown-menu drop_1\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("					    	<li><a class=\"dropdown-item\" href=\"phim/phimsapchieu.htm?tab=home\">Now Showing</a></li>\r\n");
      out.write("					    	<li><a class=\"dropdown-item border-0\" href=\"phim/phimsapchieu.htm?tab=profile\">Coming Soon</a></li>\r\n");
      out.write("		          		</ul>\r\n");
      out.write("		        	</li>\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("		          		<a class=\"nav-link\" href=\"gioithieu.htm\">About Us</a>\r\n");
      out.write("	        		</li>\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("		          		<a class=\"nav-link\" href=\"lienhe.htm\">Contact</a>\r\n");
      out.write("		        	</li>\r\n");
      out.write("		      	</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("</section>\r\n");
      out.write("<div  class=\"alert-flag \"  aType='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("		aMessage=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message.message }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("</div>\r\n");
      out.write("<main class=\"main bg-light vh-90\" style=\"background: #132028 url(https://www.bhdstar.vn/wp-content/themes/bhd/assets/images/bg-cinema-10.png) center top repeat;\">\r\n");
      out.write("        <section class=\"pt-50\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-3\">\r\n");
      out.write("                                <div class=\"dashboard-menu\">\r\n");
      out.write("                                    <ul class=\"nav flex-column\" role=\"tablist\" style=\"background-color: #fff;\">\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link active\" id=\"account-detail-tab\" data-bs-toggle=\"tab\"\r\n");
      out.write("                                                href=\"#account-detail\" role=\"tab\" aria-controls=\"account-detail\"\r\n");
      out.write("                                                aria-selected=\"true\"><i class=\"fa-regular fa-user mr-10\"></i>Personal Information</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" id=\"dashboard-tab\" data-bs-toggle=\"tab\"\r\n");
      out.write("                                                href=\"#dashboard\" role=\"tab\" aria-controls=\"dashboard\"\r\n");
      out.write("                                                aria-selected=\"false\"><i class=\"fa-solid fa-arrows-rotate mr-10\"></i>\r\n");
      out.write("                                                Change Password</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" id=\"orders-tab\" data-bs-toggle=\"tab\" href=\"#orders\"\r\n");
      out.write("                                                role=\"tab\" aria-controls=\"orders\" aria-selected=\"false\">\r\n");
      out.write("                                                <i class=\"fa-light fa-ballot mr-10\"></i>Transactions</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li class=\"nav-item\">\r\n");
      out.write("                                            <a class=\"nav-link\" href=\"/DoAnWebCinema/login/logout.htm\">\r\n");
      out.write("                                                 <i class=\"fa-solid fa-arrow-right-from-bracket mr-10\"></i>Log out</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-9\">\r\n");
      out.write("                                <div class=\"tab-content dashboard-content\">\r\n");
      out.write("                                    <div class=\"tab-pane fade\" id=\"dashboard\" role=\"tabpanel\"\r\n");
      out.write("                                        aria-labelledby=\"dashboard-tab\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"card shadow\">\r\n");
      out.write("                                            <div class=\"card-header\">\r\n");
      out.write("                                                <h5 class=\"mb-0\">Change Password</h5>\r\n");
      out.write("                                            </div>  \r\n");
      out.write("                                            <div class=\"ten\">\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <form class=\"col-4 mx-auto pt-5 card\" method=\"post\" action=\"/DoAnWebCinema/customer/change/password.htm\">\r\n");
      out.write("                                                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                            <label for=\"input-current-password\">Current Password</label>\r\n");
      out.write("                                                            <input type=\"password\" name=\"oldPass\" class=\"form-control\"\r\n");
      out.write("                                                                id=\"input-current-password\" required/>\r\n");
      out.write("                                                           ");
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                            <label for=\"input-new-password\">New Password</label>\r\n");
      out.write("                                                            <input type=\"password\" name=\"newPass\" class=\"form-control\"\r\n");
      out.write("                                                                id=\"input-new-password\" required/>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                            <label for=\"input-confirm-new-password\">Confirm new password</label>\r\n");
      out.write("                                                            <input type=\"password\" name=\"confirmPass\"\r\n");
      out.write("                                                                class=\"form-control\" id=\"input-confirm-new-password\" required/>\r\n");
      out.write("                                                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message_n}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"form-group col-12\">\r\n");
      out.write("                                                            <button type=\"submit\" name=\"btnpw\"\r\n");
      out.write("                                                                class=\"btn btn-primary col-12\">\r\n");
      out.write("                                                                Save Changes\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </form>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            </div>                                      \r\n");
      out.write("                                            \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                   <div class=\"tab-pane fade\" id=\"orders\" role=\"tabpanel\" aria-labelledby=\"orders-tab\">\r\n");
      out.write("        <div class=\"card shadow\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("                <h5 class=\"mb-0 d-flex justify-content-between align-center\">\r\n");
      out.write("                    Your Order\r\n");
      out.write("                    <form class=\"row popup\">\r\n");
      out.write("                        <div class=\"d-flex gap-1\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"order-search\" placeholder=\"Search\" />\r\n");
      out.write("                                <div class=\"input-group-text bg-brand text-white\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"popup-btn\">\r\n");
      out.write("                                <button class=\"btn\">\r\n");
      out.write("                                    <i class=\"fa fa-filter\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <div class=\"popup-card p-10\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </h5>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body shadow\">\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"col-12 bg-white p-10 rounded mb-10 bg-brand text-white\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-2 text-center\">Order Code</div>\r\n");
      out.write("						<div class=\"col-3 text-center\">Order Date</div>\r\n");
      out.write("						<div class=\"col-2 text-center\">Showtime</div>\r\n");
      out.write("						<div class=\"col-3 text-center\">Price</div>\r\n");
      out.write("						<div class=\"col-2 text-center\">Actions</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                               \r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                <div class=\"ten\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div> \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("									\r\n");
      out.write("                                    <div class=\"tab-pane fade active show\" id=\"account-detail\" role=\"tabpanel\"\r\n");
      out.write("                                        aria-labelledby=\"account-detail-tab\">\r\n");
      out.write("                                        <div class=\"card shadow\">\r\n");
      out.write("                                            <div class=\"card-header\">\r\n");
      out.write("                                                <h5>Personal Information</h5>\r\n");
      out.write("                                                ");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                           <form action=\"/DoAnWebCinema/customer/update/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.maKH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".htm\" method=\"POST\"\r\n");
      out.write("                                                            class=\"needs-validation\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                            <div class = \"ten\">\r\n");
      out.write("                                            <div class=\"card-body\">\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <div class=\"col-md-4\">\r\n");
      out.write("														    <div class=\"avatar-wrapper\">\r\n");
      out.write("														        <img class=\"profile-pic\" src=\"uploads/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.avatar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("														        <div class=\"upload-button\">\r\n");
      out.write("														            <i class=\"fa fa-arrow-circle-up\" aria-hidden=\"true\"></i>\r\n");
      out.write("														        </div>\r\n");
      out.write("														        <input class=\"file-upload\" type=\"file\" accept=\"image/*\" name=\"photo\" />\r\n");
      out.write("														    </div>\r\n");
      out.write("                                                        <div class=\"col-12 text-center text-brand-dark\">\r\n");
      out.write("                                                            <span class=\"fs-5\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"col-8\">\r\n");
      out.write("                                                            <div class=\"row\">\r\n");
      out.write("                                                                <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                                    <label>Full Name\r\n");
      out.write("                                                                        <span class=\"required\">*</span></label>\r\n");
      out.write("                                                                        <div class=\"errors\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errors_tenKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                                                    <input class=\"form-control\" name=\"tenKH\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\"\r\n");
      out.write("                                                                        required />\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <fieldset class=\"col-md-12\">\r\n");
      out.write("                                                                    <legend class=\"col-form-label col-sm-2 pt-0\">\r\n");
      out.write("                                                                        Gender\r\n");
      out.write("                                                                    </legend>\r\n");
      out.write("                                                                    <div class=\"col-sm-12 d-flex gap-4 ml-10\">\r\n");
      out.write("                                                                        <div class=\"form-check custom-radio\">\r\n");
      out.write("                                                                            <input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("                                                                                name=\"gioiTinh\" id=\"female\" value=\"false\"\r\n");
      out.write("                                                                                checked />\r\n");
      out.write("                                                                            <label class=\"form-check-label\"\r\n");
      out.write("                                                                                for=\"female\">\r\n");
      out.write("                                                                                Female\r\n");
      out.write("                                                                            </label>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                        <div class=\"form-check custom-radio\">\r\n");
      out.write("                                                                            <input class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("                                                                                name=\"gioiTinh\" id=\"male\" value=\"true\" />\r\n");
      out.write("                                                                            <label class=\"form-check-label\" for=\"male\">\r\n");
      out.write("                                                                                Male\r\n");
      out.write("                                                                            </label>\r\n");
      out.write("                                                                        </div>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </fieldset>\r\n");
      out.write("                                                                <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                                    <label>Date of Birth\r\n");
      out.write("                                                                        <span class=\"required\">*</span></label>\r\n");
      out.write("                                                                    <div class=\"errors\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errors_ngaySinh }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                                                    <input class=\"form-control\" name=\"ngaySinh\"\r\n");
      out.write("                                                                        type=\"date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.ngaySinh }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                                    <label>Address\r\n");
      out.write("                                                                        <span class=\"required\">*</span></label>\r\n");
      out.write("                                                                    <div class=\"errors\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errors_diaChi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                                                    <input  class=\"form-control\"\r\n");
      out.write("                                                                        name=\"diaChi\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.diaChi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                                <div class=\"form-group col-md-12\">\r\n");
      out.write("                                                                    <label>Phone Number\r\n");
      out.write("                                                                        <span class=\"required\">*</span></label>\r\n");
      out.write("                                                                    <div class=\"errors\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errors_soDT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                                                    <input class=\"form-control\" name=\"soDT\"\r\n");
      out.write("                                                                        type=\"tel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.soDT }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-md-12\">\r\n");
      out.write("                                                                    <button type=\"submit\" class=\"btn\" name=\"submit\"\r\n");
      out.write("                                                                        value=\"Submit\">\r\n");
      out.write("                                                                        Confirm\r\n");
      out.write("                                                                    </button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            </form>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <!-- confirm modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"confirm-modal\" tabindex=\"-1\" aria-labelledby=\"confirm-modal\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-dialog-centered modal-dialog-scrollable modal-sm\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    Are you sure you want to delete the selected product?\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text-end p-10\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn\">Confirm</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">\r\n");
      out.write("                        Cancel\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<!-- order details modal -->\r\n");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <!--  -->\r\n");
      out.write("        <script src=\"\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/vendor/modernizr-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/vendor/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/vendor/jquery-migrate-3.3.0.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/vendor/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/slick.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/jquery.syotimer.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/wow.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/jquery-ui.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/perfect-scrollbar.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/magnific-popup.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/select2.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/waypoints.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/counterup.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/images-loaded.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/isotope.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/scrollup.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/jquery.vticker-min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/jquery.theia.sticky.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/plugins/jquery.elevatezoom.js\"></script>\r\n");
      out.write("    <!-- Template  JS -->\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/account.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/shop.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/inputNumber.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/quickView.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/alertify.min.js\"></script>\r\n");
      out.write("    <script src=\"http://localhost:9999/DoAnWebCinema/js/showMessage.js\"></script>\r\n");
      out.write("	<script src=\"http://localhost:9999/DoAnWebCinema/js/alertify.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		if ($(\".alert-flag\").attr(\"aType\")) {\r\n");
      out.write("			console.log(1)\r\n");
      out.write("			alertify.notify($(\".alert-flag\").attr(\"aMessage\"), $(\".alert-flag\").attr(\"aType\"), 5, function() { console.log('dismissed'); });\r\n");
      out.write("			alertify.set('notifier', 'position', 'top-right');\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("<script>\r\n");
      out.write("    // Lấy ngày hiện tại\r\n");
      out.write("    var curDate = new Date();\r\n");
      out.write("    var date = curDate.getDate();\r\n");
      out.write("    var month = curDate.getMonth() + 1; // Tháng bắt đầu từ 0\r\n");
      out.write("    var year = curDate.getFullYear();\r\n");
      out.write("\r\n");
      out.write("    // Định dạng ngày theo định dạng yyyy-mm-dd\r\n");
      out.write("    var formattedDate = year + '-' + (month < 10 ? '0' + month : month) + '-' + (date < 10 ? '0' + date : date);\r\n");
      out.write("\r\n");
      out.write("    // Cập nhật liên kết href\r\n");
      out.write("    var link = document.getElementById('dat-ve-link');\r\n");
      out.write("    if (link) { // Kiểm tra xem phần tử có tồn tại không\r\n");
      out.write("        link.href = '/DoAnWebCinema/datve/' + formattedDate + '.htm?chinhanh=1';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    document.querySelector(\".file-upload\").addEventListener(\"change\", function() {\r\n");
      out.write("        var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("        reader.onload = function(e) {\r\n");
      out.write("            document.querySelector(\".profile-pic\").src = e.target.result;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        reader.readAsDataURL(this.files[0]);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.querySelector(\".upload-button\").addEventListener(\"click\", function() {\r\n");
      out.write("        document.querySelector(\".file-upload\").click();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("			        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/customer/account.jsp(94,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			                <p><i class=\"bi bi-person-circle\"></i><span> </span><a href=\"customer/account.htm\"><strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong></a></p>\r\n");
          out.write("			            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			                <div>\r\n");
          out.write("			                    <i class=\"bi bi-person-circle\"></i>\r\n");
          out.write("			                    <a href=\"login.htm\"><b>Login</b></a>\r\n");
          out.write("			                    <a href=\"register.htm\"><b>Sign Up</b></a>\r\n");
          out.write("			                </div>\r\n");
          out.write("			            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/customer/account.jsp(261,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("s");
      // /WEB-INF/views/customer/account.jsp(261,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/account.jsp(261,16) '${lv}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lv}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                        <div class=\"col-12 bg-white p-10 rounded-1 mb-5 product border border-brand\">\r\n");
            out.write("                            <div class=\"row align-items-center custome-checkbox\">\r\n");
            out.write("                                <div class=\"col-2 text-center product-name\">\r\n");
            out.write("                                    <h5 class=\"ten\">\r\n");
            out.write("                                        <a href=\"shop-product-right.html\" style=\"color: black\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maVe}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("                                    </h5>\r\n");
            out.write("                                </div>\r\n");
            out.write("                                <div class=\"col-3 text-center order-date\">\r\n");
            out.write("                                    <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.ngayBan}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                </div>\r\n");
            out.write("                                <div class=\"col-2 text-center product-state\">\r\n");
            out.write("                                    <span class=\"badge rounded-pill bg-brand\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.formattedGioChieu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                                </div>\r\n");
            out.write("                                <div class=\"col-3 text-center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.chiTietGhePhong.loaiGhe.gia}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                                <div class=\"col-2 d-flex justify-content-center gap-md-3 order-action\">\r\n");
            out.write("                                    <a href=\"#\" class=\"text-muted my-tooltip\" data-bs-toggle=\"modal\" data-bs-target=\"#order-details");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maVe}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" aria-label=\"Details\">\r\n");
            out.write("                                        <i class=\"fa fa-info-circle\"></i>\r\n");
            out.write("                                    </a>\r\n");
            out.write("                                </div>\r\n");
            out.write("                            </div>\r\n");
            out.write("                        </div>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/customer/account.jsp(409,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("s");
      // /WEB-INF/views/customer/account.jsp(409,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/account.jsp(409,0) '${lv}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${lv}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("    <div class=\"modal fade\" id=\"order-details");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maVe}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" tabindex=\"-1\" aria-labelledby=\"confirm-modal\" aria-hidden=\"true\">\r\n");
            out.write("        <div class=\"modal-dialog modal-dialog-centered\">\r\n");
            out.write("            <div class=\"modal-content\">\r\n");
            out.write("                <div class=\"row\">\r\n");
            out.write("                    <div class=\"col-md-12 mx-auto\">\r\n");
            out.write("                        <div class=\"order_review border-0\">\r\n");
            out.write("                            <div class=\"mb-20 d-flex justify-content-between\">\r\n");
            out.write("                                <h4>Ticket Code: <span class=\"text-brand\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.maVe}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></h4>\r\n");
            out.write("                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
            out.write("                            </div>\r\n");
            out.write("                            <div class=\"table-responsive order_table text-center\">\r\n");
            out.write("                                <table class=\"table\">\r\n");
            out.write("                                    <thead>\r\n");
            out.write("                                        <tr>\r\n");
            out.write("                                            <th colspan=\"2\">MOVIE</th>\r\n");
            out.write("                                            <th>PRICE</th>\r\n");
            out.write("                                        </tr>\r\n");
            out.write("                                    </thead>\r\n");
            out.write("                                    <tbody>\r\n");
            out.write("                                        <tr>\r\n");
            out.write("                                            <td class=\"image product-thumbnail\">\r\n");
            out.write("                                                <img src=\"/DoAnWebCinema/uploads/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.dsPhim.linkAnh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"#\" />\r\n");
            out.write("                                            </td>\r\n");
            out.write("                                            <td>\r\n");
            out.write("                                                <h5>\r\n");
            out.write("                                                    <a href=\"/DoAnWebCinema/film/detail/ma=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.dsPhim.maPhim}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".htm\" style=\"color:black\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.dsPhim.tenPhim}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("                                                </h5>\r\n");
            out.write("                                            </td>\r\n");
            out.write("                                            <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.chiTietGhePhong.loaiGhe.gia}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("                                        </tr>\r\n");
            out.write("                                        <tr>\r\n");
            out.write("											    <th>Room</th>\r\n");
            out.write("											    <td class=\"product-subtotal\" colspan=\"2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.dsPhong.maPhong}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											</tr>\r\n");
            out.write("											<tr>\r\n");
            out.write("											    <th>Seat Code</th>\r\n");
            out.write("											    <td class=\"product-subtotal\" colspan=\"2\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.chiTietGhePhong.ghe.tenGhe}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("											</tr>\r\n");
            out.write("											<tr>\r\n");
            out.write("											    <th>Showtime</th>\r\n");
            out.write("											    <td colspan=\"2\"><em>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.formattedGioChieu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(' ');
            out.write('(');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.ngayChieu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")</em></td>\r\n");
            out.write("											</tr>\r\n");
            out.write("											<tr>\r\n");
            out.write("											    <th>Total Payment</th>\r\n");
            out.write("											    <td colspan=\"2\" class=\"product-subtotal\">\r\n");
            out.write("											        <span class=\"font-xl text-brand fw-900\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.chiTietGhePhong.loaiGhe.gia}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("											    </td>\r\n");
            out.write("										</tr>\r\n");
            out.write("\r\n");
            out.write("                                    </tbody>\r\n");
            out.write("                                </table>\r\n");
            out.write("                            </div>\r\n");
            out.write("                            <div class=\"bt-1 border-color-1 mt-30 mb-30\"></div>\r\n");
            out.write("                           <div class=\"payment_method\">\r\n");
            out.write("						    <div class=\"mb-25\">\r\n");
            out.write("						        <h5>\r\n");
            out.write("						            Cinema Address:\r\n");
            out.write("						            <span class=\"text-brand\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.dsLichChieu.getDsPhong().getChiNhanh().getTenChiNhanh()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("						        </h5>\r\n");
            out.write("						    </div>\r\n");
            out.write("						</div>\r\n");
            out.write("						<div class=\"bt-1 border-color-1 mt-30 mb-30\"></div>\r\n");
            out.write("						<div class=\"payment_method\">\r\n");
            out.write("						    <div class=\"mb-25\">\r\n");
            out.write("						        <h5>\r\n");
            out.write("						            Payment Method:\r\n");
            out.write("						            <span class=\"text-brand\">Online Payment</span>\r\n");
            out.write("						        </h5>\r\n");
            out.write("						    </div>\r\n");
            out.write("						</div>\r\n");
            out.write("\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("        </div>\r\n");
            out.write("    </div>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
