/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2025-01-14 14:58:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.customer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_005f2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1390885082000L));
    _jspx_dependants.put("jar:file:/D:/HeThongThongMinh_WebCinema/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/DoAnWebCinema/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.1.RELEASE.jar", Long.valueOf(1719237896436L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1719237896340L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Ticket Booking Successful</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("    integrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/css/style_payment.css\">\r\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://localhost:9999/DoAnWebCinema/resources/fontawesome-pro-6.1.1-web/css/all.min.css\" />\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<base href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("	<link rel=\"icon\" type=\"images/png\" href=\"images/logocinema.png\">\r\n");
      out.write("	<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\" >\r\n");
      out.write("	<link href=\"css/global.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"css/index.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Rajdhani&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("	<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js\"></script>\r\n");
      out.write("  	<style>\r\n");
      out.write("  		.dropdown:hover .dropdown-menu {\r\n");
      out.write("			display: block;\r\n");
      out.write("			margin-top: 0;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.confirm-panel {\r\n");
      out.write("		    padding: 20px;\r\n");
      out.write("		    border: 1px solid #ccc;\r\n");
      out.write("		    border-radius: 8px;\r\n");
      out.write("		    background-color: #f9f9f9;\r\n");
      out.write("		    max-width: 600px;\r\n");
      out.write("		    margin: 20px auto;\r\n");
      out.write("		    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.confirm-panel-header {\r\n");
      out.write("		    text-align: center;\r\n");
      out.write("		    margin-bottom: 20px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.panel-title {\r\n");
      out.write("		    font-size: 24px;\r\n");
      out.write("		    color: #333;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.qrcode-label {\r\n");
      out.write("		    font-weight: bold;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.panel-info {\r\n");
      out.write("		    margin-top: 20px; /* Tạo khoảng cách phía trên */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.info-item {\r\n");
      out.write("		    margin-bottom: 10px;\r\n");
      out.write("		    color: #555; /* Màu chữ cho thông tin */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.edit-final {\r\n");
      out.write("		    display: flex;\r\n");
      out.write("		    justify-content: center;\r\n");
      out.write("		    margin-top: 20px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.btn {\r\n");
      out.write("		    padding: 10px 20px;\r\n");
      out.write("		    border: none;\r\n");
      out.write("		    border-radius: 5px;\r\n");
      out.write("		    cursor: pointer;\r\n");
      out.write("		    font-size: 16px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.btn-primary {\r\n");
      out.write("		    background-color: #5eb742;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("		    margin-right: 10px;\r\n");
      out.write("		    transition: background-color 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.btn-primary:hover {\r\n");
      out.write("		    background-color: #4cae50;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.btn-secondary {\r\n");
      out.write("		    background-color: #e01027;\r\n");
      out.write("		    color: #fff;\r\n");
      out.write("		    transition: background-color 0.3s ease;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.btn-secondary:hover {\r\n");
      out.write("		    background-color: #c62a34;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.qr-image {\r\n");
      out.write("		    margin-left: 50px; /* Dời mã QR một chút */\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("  	</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 	Phần đầu -->\r\n");
      out.write("	<section id=\"top\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			 <div class=\"row top_1\">\r\n");
      out.write("			 	<div class=\"col-md-3\">\r\n");
      out.write(" 				   <div class=\"top_1l pt-1\">\r\n");
      out.write("		    			<h3 class=\"mb-0\"><a class=\"text-white\" href=\"\"><i class=\"fa fa-video-camera col_red me-1\"></i>Tu Tru Cinema</a></h3>\r\n");
      out.write("		   			</div>\r\n");
      out.write("			 	</div>\r\n");
      out.write("			 	<div class=\"col-md-5\">\r\n");
      out.write("   	 				<div class=\"top_1m\">\r\n");
      out.write("    					<form class=\"col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3\" action=\"/DoAnWebCinema/search.htm\">\r\n");
      out.write("							<input type=\"search\" class=\"form-control form-control-dark\" placeholder=\"Search...\" aria-label=\"Search\" name=\"search\">\r\n");
      out.write("						</form>\r\n");
      out.write("        			</div>\r\n");
      out.write("    			</div>\r\n");
      out.write("				<div class=\"col-md-4\">\r\n");
      out.write("				    <div class=\"top_1r text-end mt-1\">\r\n");
      out.write("				        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				    </div>\r\n");
      out.write("				</div>\r\n");
      out.write("			 </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- 	Phần Menu -->\r\n");
      out.write("	<section id=\"header\">\r\n");
      out.write("		<nav class=\"navbar navbar-expand-md navbar-light\" id=\"navbar_sticky\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<a class=\"navbar-brand text-white fw-bold\" href=\"\"><i class=\"fa fa-video-camera col_red me-1\"></i>TU TRU CINEMA</a>\r\n");
      out.write("				    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("				    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("			    </button>\r\n");
      out.write("    			<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("					<ul class=\"navbar-nav mb-0\">\r\n");
      out.write("			        	<li class=\"nav-item\">\r\n");
      out.write("			          		<a class=\"nav-link active\" aria-current=\"page\" href=\"trangchu.htm\">Home</a>\r\n");
      out.write("			        	</li>\r\n");
      out.write("			     		<li class=\"nav-item\">\r\n");
      out.write("			          		<a id=\"dat-ve-link\" class=\"nav-link\" href=\"#\">Book Now</a>\r\n");
      out.write("			        	</li>\r\n");
      out.write("			        	<li class=\"nav-item dropdown\">\r\n");
      out.write("			          		<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Movie</a>\r\n");
      out.write("			          		<ul class=\"dropdown-menu drop_1\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("						    	<li><a class=\"dropdown-item\" href=\"phim/phimsapchieu.htm?tab=home\">Now Showing</a></li>\r\n");
      out.write("						    	<li><a class=\"dropdown-item border-0\" href=\"phim/phimsapchieu.htm?tab=profile\">Coming Soon</a></li>\r\n");
      out.write("			          		</ul>\r\n");
      out.write("			        	</li>\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("			          		<a class=\"nav-link\" href=\"gioithieu.htm\">About Us</a>\r\n");
      out.write("		        		</li>\r\n");
      out.write("						<li class=\"nav-item\">\r\n");
      out.write("			          		<a class=\"nav-link\" href=\"lienhe.htm\">Contact</a>\r\n");
      out.write("			        	</li>\r\n");
      out.write("			      	</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("	</section>\r\n");
      out.write("<!---->\r\n");
      out.write("  <div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Tab items -->\r\n");
      out.write("    <div class=\"tabs\">\r\n");
      out.write("      <!-- <div class=\"tab-item active\">\r\n");
      out.write("        <span class=\"selected-ticket\">1. Chọn Vé</span>\r\n");
      out.write("      </div> -->\r\n");
      out.write("      <div class=\"tab-item\" id=\"tab-item-1\">\r\n");
      out.write("        <span class=\"selected-ticket\" id=\"tab-item-1\">1. Select Tickets</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"tab-item\" id=\"tab-item-2\">\r\n");
      out.write("        <span class=\"selected-ticket\">2. Payment</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"tab-item active\" id=\"tab-item-3\">\r\n");
      out.write("        <span class=\"selected-ticket\">3. Confirmation</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Tab content -->\r\n");
      out.write("    <div class=\"tab-content\">\r\n");
      out.write("    <div class=\"tab-pane active\" id=\"tab-pane-2\">\r\n");
      out.write("        <div class=\"confirm-panel\">\r\n");
      out.write("            <div class=\"confirm-panel-header\">\r\n");
      out.write("                <h3 class=\"panel-title\">TICKET BOOKING SUCCESSFUL!</h3>\r\n");
      out.write("                <p>Thank you for booking your tickets. Below is your booking information:</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"confirm-panel-content\">\r\n");
      out.write("                <div class=\"panel-qrcode\">\r\n");
      out.write("                    <span class=\"qrcode-label\">Room Access Code:</span>\r\n");
      out.write("                    <div class=\"qr-image\" id=\"qrcode\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("				<div class=\"panel-info\">\r\n");
      out.write("				    <div class=\"info-item\"><b>Seat List:</b> <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ghe}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\r\n");
      out.write("					<div class=\"info-item\"><b>Theater:</b> <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.getDsPhong().getChiNhanh().getTenChiNhanh()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\r\n");
      out.write("					<div class=\"info-item\"><b>Movie:</b> <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.dsPhim.tenPhim}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\r\n");
      out.write("					<div class=\"info-item\"><b>Showtime:</b> <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.formattedGioChieu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.ngayChieu}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></div>\r\n");
      out.write("					<div class=\"info-item\"><b>Total Payment:</b> <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tongTien}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></div>\r\n");
      out.write("				</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"edit-final\">\r\n");
      out.write("                <form action=\"/DoAnWebCinema/customer/payment/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lc.maSC}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".htm\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-continue1\">Book Again</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <form action=\"/DoAnWebCinema/\">\r\n");
      out.write("                    <button class=\"btn btn-secondary\" type=\"submit\">Home</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Lấy ngày hiện tại\r\n");
      out.write("    var curDate = new Date();\r\n");
      out.write("    var date = curDate.getDate();\r\n");
      out.write("    var month = curDate.getMonth() + 1; // Tháng bắt đầu từ 0\r\n");
      out.write("    var year = curDate.getFullYear();\r\n");
      out.write("\r\n");
      out.write("    // Định dạng ngày theo định dạng yyyy-mm-dd\r\n");
      out.write("    var formattedDate = year + '-' + (month < 10 ? '0' + month : month) + '-' + (date < 10 ? '0' + date : date);\r\n");
      out.write("\r\n");
      out.write("    // Cập nhật liên kết href\r\n");
      out.write("    var link = document.getElementById('dat-ve-link');\r\n");
      out.write("    if (link) { // Kiểm tra xem phần tử có tồn tại không\r\n");
      out.write("        link.href = '/DoAnWebCinema/datve/' + formattedDate + '.htm?chinhanh=1';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("    // Hàm tạo mã QR\r\n");
      out.write("    function generateQRCode(text) {\r\n");
      out.write("        $('#qrcode').empty(); // Xóa mã QR cũ\r\n");
      out.write("        $('#qrcode').qrcode({\r\n");
      out.write("            text: text,\r\n");
      out.write("            width: 128,\r\n");
      out.write("            height: 128\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Gọi hàm tạo mã QR với giá trị khác nhau\r\n");
      out.write("    const roomCode = \"MaPhong_\" + Math.floor(Math.random() * 10000); // Tạo mã phòng ngẫu nhiên\r\n");
      out.write("    generateQRCode(roomCode);\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/customer/payment_2.jsp(133,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				                <p><i class=\"bi bi-person-circle\"></i><span> </span><a href=\"customer/account.htm\"><strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.tenKH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong></a></p>\r\n");
          out.write("				            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				                <div>\r\n");
          out.write("				                    <i class=\"bi bi-person-circle\"></i>\r\n");
          out.write("				                    <a href=\"login.htm\"><b>Login</b></a>\r\n");
          out.write("				                    <a href=\"register.htm\"><b>Sign Up</b></a>\r\n");
          out.write("				                </div>\r\n");
          out.write("				            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
